# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('effect', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Damage_Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Damage_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Generations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.CharField(max_length=25)),
                ('abilities', models.ManyToManyField(related_name='generation', to='dex_app.Abilities')),
            ],
        ),
        migrations.CreateModel(
            name='Learn_Methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('pp', models.IntegerField()),
                ('power', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='dex_app.Damage_Types')),
            ],
        ),
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('entries', models.ManyToManyField(related_name='pokedex', to='dex_app.Entries')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bst', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('abilities', models.ManyToManyField(related_name='pokemon', to='dex_app.Abilities')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon_Learns_Move_By_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meth_qual', models.CharField(max_length=10)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_learns_move_by', to='dex_app.Learn_Methods')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_learns_by_method', to='dex_app.Moves')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learns_move_by_method', to='dex_app.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('move_learn_methods', models.ManyToManyField(related_name='version', to='dex_app.Learn_Methods')),
                ('pokedexes', models.ManyToManyField(related_name='generation', to='dex_app.Pokedex')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemon', to='dex_app.Types'),
        ),
        migrations.AddField(
            model_name='moves',
            name='tipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='dex_app.Types'),
        ),
        migrations.AddField(
            model_name='generations',
            name='moves',
            field=models.ManyToManyField(related_name='generation', to='dex_app.Moves'),
        ),
        migrations.AddField(
            model_name='generations',
            name='pokemon',
            field=models.ManyToManyField(related_name='generation', to='dex_app.Pokemon'),
        ),
        migrations.AddField(
            model_name='generations',
            name='types',
            field=models.ManyToManyField(related_name='generation', to='dex_app.Types'),
        ),
        migrations.AddField(
            model_name='generations',
            name='versions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation', to='dex_app.Versions'),
        ),
        migrations.AddField(
            model_name='entries',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='dex_app.Pokemon'),
        ),
        migrations.AddField(
            model_name='damage_relationships',
            name='double_from',
            field=models.ManyToManyField(related_name='double_to', to='dex_app.Types'),
        ),
        migrations.AddField(
            model_name='damage_relationships',
            name='double_to',
            field=models.ManyToManyField(related_name='double_from', to='dex_app.Types'),
        ),
        migrations.AddField(
            model_name='damage_relationships',
            name='half_from',
            field=models.ManyToManyField(related_name='half_to', to='dex_app.Types'),
        ),
        migrations.AddField(
            model_name='damage_relationships',
            name='half_to',
            field=models.ManyToManyField(related_name='half_from', to='dex_app.Types'),
        ),
        migrations.AddField(
            model_name='damage_relationships',
            name='none_from',
            field=models.ManyToManyField(related_name='none_to', to='dex_app.Types'),
        ),
        migrations.AddField(
            model_name='damage_relationships',
            name='none_to',
            field=models.ManyToManyField(related_name='nome_from', to='dex_app.Types'),
        ),
        migrations.AddField(
            model_name='damage_relationships',
            name='tipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_relationship', to='dex_app.Types'),
        ),
    ]
