# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moves',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
