# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0002_moves_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generations',
            name='pokemon',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(related_name='pokemon_with_ability', to='dex_app.Abilities'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemon_of_type', to='dex_app.Types'),
        ),
    ]
