# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0003_auto_20181120_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='generations',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='generations',
            name='moves',
        ),
        migrations.RemoveField(
            model_name='generations',
            name='types',
        ),
        migrations.RemoveField(
            model_name='generations',
            name='versions',
        ),
        migrations.RemoveField(
            model_name='pokedex',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='pokemon_learns_move_by_method',
            name='method',
        ),
        migrations.RemoveField(
            model_name='pokemon_learns_move_by_method',
            name='move',
        ),
        migrations.RemoveField(
            model_name='pokemon_learns_move_by_method',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='versions',
            name='move_learn_methods',
        ),
        migrations.RemoveField(
            model_name='versions',
            name='pokedexes',
        ),
        migrations.DeleteModel(
            name='Entries',
        ),
        migrations.DeleteModel(
            name='Generations',
        ),
        migrations.DeleteModel(
            name='Learn_Methods',
        ),
        migrations.DeleteModel(
            name='Pokedex',
        ),
        migrations.DeleteModel(
            name='Pokemon_Learns_Move_By_Method',
        ),
        migrations.DeleteModel(
            name='Versions',
        ),
    ]
