# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0004_auto_20181120_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Generations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.CharField(max_length=25)),
                ('abilities', models.ManyToManyField(related_name='generation', to='dex_app.Abilities')),
            ],
        ),
        migrations.CreateModel(
            name='Learn_Methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('entries', models.ManyToManyField(related_name='pokedex', to='dex_app.Entries')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon_Learns_Move_By_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meth_qual', models.CharField(max_length=10)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_learns_move_by', to='dex_app.Learn_Methods')),
            ],
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('move_learn_methods', models.ManyToManyField(related_name='version', to='dex_app.Learn_Methods')),
                ('pokedexes', models.ManyToManyField(related_name='generation', to='dex_app.Pokedex')),
            ],
        ),
        migrations.RemoveField(
            model_name='moves',
            name='category',
        ),
        migrations.AddField(
            model_name='moves',
            name='category',
            field=models.ManyToManyField(related_name='moves', to='dex_app.Damage_Types'),
        ),
        migrations.RemoveField(
            model_name='moves',
            name='tipe',
        ),
        migrations.AddField(
            model_name='moves',
            name='tipe',
            field=models.ManyToManyField(related_name='moves', to='dex_app.Types'),
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_with_ability', to='dex_app.Abilities'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_of_type', to='dex_app.Types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon_learns_move_by_method',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_learns_by_method', to='dex_app.Moves'),
        ),
        migrations.AddField(
            model_name='pokemon_learns_move_by_method',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learns_move_by_method', to='dex_app.Pokemon'),
        ),
        migrations.AddField(
            model_name='generations',
            name='moves',
            field=models.ManyToManyField(related_name='generation', to='dex_app.Moves'),
        ),
        migrations.AddField(
            model_name='generations',
            name='types',
            field=models.ManyToManyField(related_name='generation', to='dex_app.Types'),
        ),
        migrations.AddField(
            model_name='generations',
            name='versions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation', to='dex_app.Versions'),
        ),
        migrations.AddField(
            model_name='entries',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='dex_app.Pokemon'),
        ),
    ]
