# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0005_auto_20181120_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(related_name='pokemon_with_ability', to='dex_app.Abilities'),
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemon_of_type', to='dex_app.Types'),
        ),
    ]
