# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0006_auto_20181120_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moves',
            name='category',
        ),
        migrations.AddField(
            model_name='moves',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='dex_app.Damage_Types'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='moves',
            name='tipe',
        ),
        migrations.AddField(
            model_name='moves',
            name='tipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='dex_app.Types'),
            preserve_default=False,
        ),
    ]
