# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0009_auto_20181120_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves',
            name='accuracy',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='moves',
            name='power',
            field=models.CharField(max_length=25),
        ),
    ]
