# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0010_auto_20181120_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versions',
            name='move_learn_methods',
        ),
        migrations.RemoveField(
            model_name='versions',
            name='pokedexes',
        ),
        migrations.AddField(
            model_name='generations',
            name='pokemon',
            field=models.ManyToManyField(related_name='generation', to='dex_app.Pokemon'),
        ),
    ]
