# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0011_auto_20181120_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='generations',
            name='dex_to',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
