# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0013_auto_20181120_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='versions',
            name='gen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dex_app.Generations'),
            preserve_default=False,
        ),
    ]
