# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0014_versions_gen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generations',
            name='pokemon',
        ),
    ]
