# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0015_remove_generations_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon_learns_move_by_method',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_learns_move_by_method', to='dex_app.Versions'),
            preserve_default=False,
        ),
    ]
