# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0016_pokemon_learns_move_by_method_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon_learns_move_by_method',
            name='meth_qual',
            field=models.IntegerField(),
        ),
    ]
